### ISSUE TITLE
making legend interactive with raycaster

### ISSUE THREAD

**Issue by gabrieljbaker** [adrixp/aframe-charts-component#9]
I am trying to use the legend and have gotten the legend to appear, but I can't get the values to change based on clicking different segments of the pie chart. I have my raycaster set to only click on objects with data-raycastable attribute, but I'm not sure the cylinders being created for the piegraph have that attribute. 

Is there any way I can add it to them, or ensure that my raycaster will work with the created entities for the graph?

**Comment by adrixp** [comment]
Hi @gabrieljbaker 

You can add an entity in order to solve that:
<a-entity laser-controls="hand: left"></a-entity>
<a-entity laser-controls="hand: right"></a-entity>

I have an example in this [link](https://github.com/adrixp/aframe-charts-component/blob/master/examples/museum/index.html)

Anyway you can visit [A-Frame Documentation](https://aframe.io/docs/1.0.0/components/laser-controls.html#sidebar) in order to see more about raycaster and choose your preferred for your specific device

Tell me if this helps you
Greetings
